[package]
name = "godsays"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Samuel Åkesson <https://github.com/sermuns>"]
license = "Unlicense"
description = "Holy alternative to #lorem"
repository = "https://github.com/sermuns/typst-godsays"
categories = ["fun", "text"]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]
